server:
  port: 8059
#  servlet:
#    context-path: /test

#mysql配置
spring:
  datasource:
    url: jdbc:mysql://@service.address@:3306/spell_mall?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: @mysql.user@
    password: @mysql.password@
    driver-class-name: com.mysql.cj.jdbc.Driver
    #Hikari 连接池配置
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 连接池最大连接数，默认是10
      maximum-pool-size: 100
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池母子
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 30000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # 上传文件大小设置
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

    #redis
  redis:
    database: 15
    host: @service.address@
    password: @redis.password@
    port: 6379

    #mybatis
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  type-aliases-package: com.rcloud.spellentity.entity

  #日志
logging:
  level:
    com.rcloud.spelldao.dao: @logging.level@

    # pagehelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#阿里oos配置
ossConfig:
  #Endpoint  请按实际情况填写
  endpoint: https://oss-cn-beijing.aliyuncs.com/
  #阿里云主账号AccessKey
  accessKeyId: LTAIXRm6Umwgu5R2
  #阿里云主账号AccessKeySecret
  accessKeySecret: mClIjOKZ0TlR1M5Z0ylYVHqOAUNBl2
  #储存空间名称
  bucketName: hanchuig
  #返回URL
  resultUrl: https://hanchuig.oss-cn-beijing.aliyuncs.com/


wxConfig:
  appId: wx6517d517c844dd15
  secret: dc144472dd4e87ef00372158547eae3d
  callBack: http://ninelives.imwork.net/userOrder/callback

wxpay:
  enabled: true
  app-id: wx6517d517c844dd15
  mch-id: 1500793841
  pay-key: H68LB0G5CyeFArcYleQh93GYJP6U2a8X